name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'README.md'
    - '.gitignore'
  pull_request:

jobs:
  build:
    name: Build and test yay
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1#
      - name: Run Build and tests
        run: ./testdata/ci/full.sh
      - uses: actions/upload-artifact@master
        with:
          name: yay_release
          path: artifacts
  tag:
    if: contains(github.ref, 'master')
    name: Tag release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
