name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'README.md'
    - '.gitignore'
    - 'CHANGELOG.md'
  pull_request:

jobs:
  build:
    name: Build and test yay
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1#
      - name: Run Build and tests
        run: ./testdata/ci/full.sh
      - uses: actions/upload-artifact@master
        with:
          name: yay_release
          path: artifacts
  tag:
    if: contains(github.ref, 'master')
    name: Tag release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate changelog
      uses: zthulj/changelog-and-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: jguer
        LOG_LEVEL: 1
